### ISSUE TITLE
std::is_base_of<TelemetryContainer, T>::value does not always seem to compile (OS dependent?)

### ISSUE THREAD

**Issue by CasperBroekhuizen** [DelfiSpace/DelfiPQcore#14]
in HousekeepingService.h a check is done to make sure the template class is a inherited class from the TelemetryContainer baseclass. std::is_base_of is used for this, however this does not always seem to compile properly.

**Comment by StefanoSperetta** [comment]
Can you check this folder (under Windows): Application folder/ccs910/ccs/tools/compiler/ti-cgt-arm_18.12.4.LTS/lib/src/libcxx

Do you see a file named type_traits (no extension)?

**Comment by CasperBroekhuizen** [comment]
Yes, C:\ti\ccs920\ccs\tools\compiler\ti-cgt-arm_18.12.3.LTS\lib\src\libcxx\type_traits is present

**Comment by StefanoSperetta** [comment]
Can you try to switch to the newest compiler (ti-cgt-arm_18.12.4.LTS) in the project properties and try again?

**Comment by CasperBroekhuizen** [comment]
Downloaded and installed the newer compiler and switched. However, the line still gets underlined as unresolved. However, when you manually delete the errors, and compile. It does succeed.

**Comment by StefanoSperetta** [comment]
This seems to be a nasty bug in code composer: the file is present under windows but, if the file HousekeepingService.h file is open in the editor, an error is triggered.

The workaround is closing the file, manually deleting the error in the Output tab and recompiling the 
 project.

The issue is only present under Windows.
